"""Built-in plot template catalog."""

from __future__ import annotations

from typing import Any

from app.models_plot import PlotTemplateSpec


def builtin_plot_templates() -> list[dict[str, Any]]:
    from app.models_plot import PlotTemplatePoint

    def point(
        point_id: str,
        title: str,
        claim: str,
        order: int,
        *,
        phase: str = "",
        min_position: float | None = None,
        max_position: float | None = None,
        questions: list[str] | None = None,
        failures: list[str] | None = None,
        evidence: list[str] | None = None,
        guidance: str = "",
        metadata: dict[str, Any] | None = None,
    ) -> PlotTemplatePoint:
        del order, phase, min_position, max_position, questions, failures, evidence
        return PlotTemplatePoint(
            id=point_id,
            title=title,
            function_claim=claim,
            guidance=guidance,
            metadata=metadata or {},
        )

    def template(
        filename: str,
        node_id: str,
        title: str,
        body: str,
        *,
        slug: str,
        family: str,
        points: list[PlotTemplatePoint],
        cultural_context: str = "",
        ip_risk: str = "low",
        source_note: str = "Generic structure guidance authored for the app, not imported from a protected beat sheet.",
        source_url: str | None = None,
    ) -> dict[str, Any]:
        return {
            "filename": filename,
            "node_id": node_id,
            "title": title,
            "body": body,
            "template": PlotTemplateSpec(
                slug=slug,
                display_name=title,
                family=family,
                description=body,
                cultural_context=cultural_context,
                prescriptiveness="diagnostic",
                ai_use_guidance=(
                    "Use as an elastic diagnostic lens. Do not treat plot points as chapter slots "
                    "or require every point to be isolated in its own scene."
                ),
                global_diagnostic_questions=[
                    "Which story state changes because of this beat?",
                    "Which cards or scenes provide evidence for the function marker?",
                    "Does the set of claimed cards make the beat feel earned?",
                ],
                source_refs=[
                    {
                        "id": "local_writing_app_generic",
                        "title": "Local Writing App generic plotting rubric",
                        "url": source_url,
                        "note": source_note,
                    }
                ],
                ip_risk=ip_risk,
                builtin_policy="seed_generic",
                template_version="1.0",
                locale="en",
                plot_points=points,
            ),
        }

    return [
        template(
            "Three Act Structure.md",
            "plot_template_three_act",
            "Three-Act Story Arc",
            "A generic three-part structure template. Duplicate into the book plot folder before editing.",
            slug="three-act-story-arc",
            family="act",
            points=[
                point(
                    "setup_pressure",
                    "Setup pressure",
                    "Establishes ordinary conditions, desire, and pressure before commitment.",
                    1,
                    phase="Act I",
                    min_position=0,
                    max_position=0.25,
                ),
                point(
                    "inciting_change",
                    "Inciting change",
                    "Introduces a disruption the protagonist cannot fully ignore.",
                    2,
                    phase="Act I",
                    min_position=0.05,
                    max_position=0.2,
                ),
                point(
                    "first_turn",
                    "First turn",
                    "Makes the old path unavailable and commits the story to its central problem.",
                    3,
                    phase="Act I / Act II hinge",
                    min_position=0.2,
                    max_position=0.3,
                ),
                point(
                    "midpoint_reversal",
                    "Midpoint reversal",
                    "Changes the power balance, information state, or strategy.",
                    4,
                    phase="Act II",
                    min_position=0.45,
                    max_position=0.55,
                ),
                point(
                    "crisis",
                    "Crisis",
                    "Forces the hard choice before resolution.",
                    5,
                    phase="Act II / Act III hinge",
                    min_position=0.7,
                    max_position=0.82,
                ),
                point(
                    "climax",
                    "Climax",
                    "Tests the final choice in irreversible action.",
                    6,
                    phase="Act III",
                    min_position=0.82,
                    max_position=0.96,
                ),
                point(
                    "resolution",
                    "Resolution",
                    "Shows the consequence of the final choice.",
                    7,
                    phase="Act III",
                    min_position=0.9,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Fifteen-Beat Transformation Arc.md",
            "plot_template_fifteen_beat_transformation",
            "Fifteen-Beat Transformation Arc",
            "A generic fifteen-beat transformation lens with original labels and wording.",
            slug="fifteen-beat-transformation-arc",
            family="act",
            ip_risk="medium",
            source_note="Safe generic alternative to branded fifteen-beat craft systems; avoid implying affiliation with any third-party method.",
            points=[
                point(
                    "opening_state",
                    "Opening state",
                    "Shows the protagonist and world before pressure changes them.",
                    1,
                    phase="Opening",
                    min_position=0,
                    max_position=0.08,
                ),
                point(
                    "theme_pressure",
                    "Theme pressure",
                    "Raises the value question the story will test.",
                    2,
                    phase="Opening",
                    min_position=0.02,
                    max_position=0.12,
                ),
                point(
                    "setup_web",
                    "Setup web",
                    "Plants relationships, wants, lacks, and practical stakes.",
                    3,
                    phase="Opening",
                    min_position=0.05,
                    max_position=0.18,
                ),
                point(
                    "catalyst",
                    "Catalyst",
                    "Delivers the disruption that creates story motion.",
                    4,
                    phase="Opening turn",
                    min_position=0.08,
                    max_position=0.18,
                ),
                point(
                    "choice_debate",
                    "Choice debate",
                    "Lets the protagonist weigh avoidance, risk, and desire.",
                    5,
                    phase="Opening turn",
                    min_position=0.1,
                    max_position=0.25,
                ),
                point(
                    "new_world_entry",
                    "New world entry",
                    "Moves the protagonist into the story's main pressure field.",
                    6,
                    phase="Middle entry",
                    min_position=0.2,
                    max_position=0.3,
                ),
                point(
                    "promise_play",
                    "Promise play",
                    "Explores the premise, genre engine, and expected pleasures.",
                    7,
                    phase="Middle",
                    min_position=0.25,
                    max_position=0.5,
                ),
                point(
                    "central_shift",
                    "Central shift",
                    "Reframes the visible win, loss, or understanding of the problem.",
                    8,
                    phase="Middle",
                    min_position=0.45,
                    max_position=0.55,
                ),
                point(
                    "opposition_closes",
                    "Opposition closes",
                    "Increases pressure from antagonists, consequences, or inner resistance.",
                    9,
                    phase="Middle pressure",
                    min_position=0.5,
                    max_position=0.7,
                ),
                point(
                    "apparent_loss",
                    "Apparent loss",
                    "Makes the current strategy fail in a way that cannot be hand-waved.",
                    10,
                    phase="Late middle",
                    min_position=0.65,
                    max_position=0.78,
                ),
                point(
                    "dark_reckoning",
                    "Dark reckoning",
                    "Lets the protagonist face the cost, lie, or impossible bargain.",
                    11,
                    phase="Late middle",
                    min_position=0.7,
                    max_position=0.82,
                ),
                point(
                    "solution_synthesis",
                    "Solution synthesis",
                    "Combines learned truth with practical action.",
                    12,
                    phase="Final turn",
                    min_position=0.75,
                    max_position=0.88,
                ),
                point(
                    "final_plan",
                    "Final plan",
                    "Commits to the ending strategy and its cost.",
                    13,
                    phase="Finale",
                    min_position=0.8,
                    max_position=0.92,
                ),
                point(
                    "final_test",
                    "Final test",
                    "Proves the changed strategy under maximum pressure.",
                    14,
                    phase="Finale",
                    min_position=0.88,
                    max_position=0.98,
                ),
                point(
                    "final_state",
                    "Final state",
                    "Shows the transformed world, self, or relationship.",
                    15,
                    phase="Close",
                    min_position=0.94,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Mythic Quest Arc.md",
            "plot_template_mythic_quest",
            "Mythic Quest Arc",
            "A generic mythic journey lens for departure, ordeal, return, and integration.",
            slug="mythic-quest-arc",
            family="journey",
            source_url="https://www.jcf.org/learn/joseph-campbell-heros-journey",
            points=[
                point(
                    "known_world",
                    "Known world",
                    "Establishes the protagonist's starting order and its limits.",
                    1,
                    phase="Departure",
                    min_position=0,
                    max_position=0.12,
                ),
                point(
                    "call_to_change",
                    "Call to change",
                    "Invites or forces movement beyond the known world.",
                    2,
                    phase="Departure",
                    min_position=0.08,
                    max_position=0.22,
                ),
                point(
                    "threshold",
                    "Threshold",
                    "Crosses into a space where old rules no longer suffice.",
                    3,
                    phase="Departure",
                    min_position=0.18,
                    max_position=0.32,
                ),
                point(
                    "tests_allies_enemies",
                    "Tests, allies, enemies",
                    "Builds pressure through trials, bargains, helpers, and opposition.",
                    4,
                    phase="Initiation",
                    min_position=0.25,
                    max_position=0.55,
                ),
                point(
                    "central_ordeal",
                    "Central ordeal",
                    "Confronts the protagonist with the story's deepest test.",
                    5,
                    phase="Initiation",
                    min_position=0.45,
                    max_position=0.7,
                ),
                point(
                    "boon_or_cost",
                    "Boon or cost",
                    "Obtains knowledge, power, loss, or obligation that changes the return.",
                    6,
                    phase="Initiation",
                    min_position=0.55,
                    max_position=0.78,
                ),
                point(
                    "return_pressure",
                    "Return pressure",
                    "Forces the boon or change back toward the original world.",
                    7,
                    phase="Return",
                    min_position=0.7,
                    max_position=0.88,
                ),
                point(
                    "integrated_return",
                    "Integrated return",
                    "Shows what the journey changes for self and community.",
                    8,
                    phase="Return",
                    min_position=0.86,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Twelve-Step Quest Arc.md",
            "plot_template_twelve_step_quest",
            "Twelve-Step Quest Arc",
            "A generic twelve-step quest structure with rephrased labels and elastic placement.",
            slug="twelve-step-quest-arc",
            family="journey",
            ip_risk="medium",
            source_note="Generic quest arc inspired by common journey structures; avoid copying specific third-party stage text or diagrams.",
            points=[
                point(
                    "starting_order",
                    "Starting order",
                    "Shows the world and identity before disruption.",
                    1,
                    phase="Departure",
                    min_position=0,
                    max_position=0.1,
                ),
                point(
                    "summons",
                    "Summons",
                    "Presents the invitation, threat, or need that calls for change.",
                    2,
                    phase="Departure",
                    min_position=0.05,
                    max_position=0.18,
                ),
                point(
                    "resistance",
                    "Resistance",
                    "Shows why the protagonist cannot or will not engage yet.",
                    3,
                    phase="Departure",
                    min_position=0.08,
                    max_position=0.22,
                ),
                point(
                    "guidance",
                    "Guidance",
                    "Offers tools, warning, model, or misleading counsel.",
                    4,
                    phase="Departure",
                    min_position=0.12,
                    max_position=0.28,
                ),
                point(
                    "crossing",
                    "Crossing",
                    "Commits the protagonist to unfamiliar rules.",
                    5,
                    phase="Departure",
                    min_position=0.2,
                    max_position=0.32,
                ),
                point(
                    "trial_network",
                    "Trial network",
                    "Tests skill, loyalty, desire, and perception.",
                    6,
                    phase="Initiation",
                    min_position=0.28,
                    max_position=0.52,
                ),
                point(
                    "deep_approach",
                    "Deep approach",
                    "Narrows options before the central ordeal.",
                    7,
                    phase="Initiation",
                    min_position=0.42,
                    max_position=0.62,
                ),
                point(
                    "ordeal",
                    "Ordeal",
                    "Tests the protagonist at a symbolic or practical death point.",
                    8,
                    phase="Initiation",
                    min_position=0.5,
                    max_position=0.7,
                ),
                point(
                    "reward",
                    "Reward",
                    "Gains a boon, truth, wound, or leverage from the ordeal.",
                    9,
                    phase="Initiation",
                    min_position=0.58,
                    max_position=0.75,
                ),
                point(
                    "return_route",
                    "Return route",
                    "Drives the changed protagonist back toward consequence.",
                    10,
                    phase="Return",
                    min_position=0.68,
                    max_position=0.85,
                ),
                point(
                    "last_transformation",
                    "Last transformation",
                    "Requires the deepest change to survive the ending pressure.",
                    11,
                    phase="Return",
                    min_position=0.78,
                    max_position=0.95,
                ),
                point(
                    "boon_shared",
                    "Boon shared",
                    "Shows the changed relationship between protagonist, world, and gift.",
                    12,
                    phase="Return",
                    min_position=0.9,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Heroine Journey.md",
            "plot_template_heroine_journey",
            "Integration Journey",
            "A generic internal-integration journey template. Duplicate into the book plot folder before editing.",
            slug="integration-journey",
            family="journey",
            ip_risk="medium",
            source_url="https://maureenmurdock.com/the-heroines-journey/",
            source_note="Safe generic integration journey; exact third-party stage names and explanatory text are not bundled.",
            points=[
                point(
                    "identity_pressure",
                    "Identity pressure",
                    "Shows the inherited role, value system, or belonging that no longer fits.",
                    1,
                    phase="Separation",
                    min_position=0,
                    max_position=0.18,
                ),
                point(
                    "adaptation_strategy",
                    "Adaptation strategy",
                    "Shows the survival strategy that wins approval while splitting the self.",
                    2,
                    phase="Separation",
                    min_position=0.12,
                    max_position=0.32,
                ),
                point(
                    "outer_success_inner_cost",
                    "Outer success, inner cost",
                    "Lets achievement expose depletion, isolation, or spiritual dryness.",
                    3,
                    phase="Road of trials",
                    min_position=0.25,
                    max_position=0.55,
                ),
                point(
                    "descent",
                    "Descent",
                    "Pressure exposes the limits of the old survival strategy.",
                    4,
                    phase="Descent",
                    min_position=0.45,
                    max_position=0.72,
                ),
                point(
                    "reconnection",
                    "Reconnection",
                    "The protagonist claims or rebuilds a needed source of belonging.",
                    5,
                    phase="Reconnection",
                    min_position=0.62,
                    max_position=0.86,
                ),
                point(
                    "integration",
                    "Integration",
                    "Inner and outer choices align in action.",
                    6,
                    phase="Integration",
                    min_position=0.82,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Circular Change Arc.md",
            "plot_template_circular_change",
            "Circular Change Arc",
            "A generic eight-part change cycle usable at scene, episode, subplot, or book scale.",
            slug="circular-change-arc",
            family="cycle",
            source_url="https://reedsy.com/blog/guide/story-structure/dan-harmon-story-circle/",
            points=[
                point(
                    "comfort",
                    "Comfort",
                    "Shows the known state before desire pulls the character outward.",
                    1,
                    phase="Known",
                    min_position=0,
                    max_position=0.12,
                ),
                point(
                    "need",
                    "Need",
                    "Clarifies the want, lack, or pressure that breaks stasis.",
                    2,
                    phase="Known",
                    min_position=0.08,
                    max_position=0.22,
                ),
                point(
                    "go",
                    "Go",
                    "Moves into an unfamiliar situation or tactic.",
                    3,
                    phase="Unknown",
                    min_position=0.18,
                    max_position=0.35,
                ),
                point(
                    "search",
                    "Search",
                    "Forces adaptation through pursuit, trial, or improvisation.",
                    4,
                    phase="Unknown",
                    min_position=0.3,
                    max_position=0.55,
                ),
                point(
                    "find",
                    "Find",
                    "Reaches the apparent goal or discovers what the goal really costs.",
                    5,
                    phase="Unknown",
                    min_position=0.45,
                    max_position=0.68,
                ),
                point(
                    "take_cost",
                    "Take the cost",
                    "Pays for the gain with loss, compromise, or irreversible change.",
                    6,
                    phase="Unknown",
                    min_position=0.58,
                    max_position=0.78,
                ),
                point(
                    "return",
                    "Return",
                    "Carries the changed self or prize back toward the known world.",
                    7,
                    phase="Known",
                    min_position=0.72,
                    max_position=0.9,
                ),
                point(
                    "changed",
                    "Changed",
                    "Shows the contrast between the initial and final state.",
                    8,
                    phase="Known",
                    min_position=0.86,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Seven-Point Plot Arc.md",
            "plot_template_seven_point",
            "Seven-Point Plot Arc",
            "A generic seven-point plot lens organized around ending contrast, turns, pressure points, and resolution.",
            slug="seven-point-plot-arc",
            family="act",
            source_url="https://writingexcuses.com/writing-excuses-7-41-seven-point-story-structure/",
            points=[
                point(
                    "hook",
                    "Hook",
                    "Shows the initial state that will contrast with the resolution.",
                    1,
                    phase="Opening",
                    min_position=0,
                    max_position=0.12,
                ),
                point(
                    "first_turn",
                    "First plot turn",
                    "Introduces the central conflict or opportunity that moves the story forward.",
                    2,
                    phase="First turn",
                    min_position=0.18,
                    max_position=0.32,
                ),
                point(
                    "first_pinch",
                    "First pressure point",
                    "Applies antagonistic pressure that proves the problem is real.",
                    3,
                    phase="Early middle",
                    min_position=0.3,
                    max_position=0.42,
                ),
                point(
                    "midpoint_shift",
                    "Midpoint shift",
                    "Moves the protagonist from reaction toward action.",
                    4,
                    phase="Middle",
                    min_position=0.45,
                    max_position=0.55,
                ),
                point(
                    "second_pinch",
                    "Second pressure point",
                    "Tightens stakes and removes easy paths.",
                    5,
                    phase="Late middle",
                    min_position=0.58,
                    max_position=0.72,
                ),
                point(
                    "second_turn",
                    "Second plot turn",
                    "Provides the final missing insight, resource, or decision path.",
                    6,
                    phase="Final turn",
                    min_position=0.7,
                    max_position=0.85,
                ),
                point(
                    "resolution",
                    "Resolution",
                    "Pays off the hook by showing the changed ending state.",
                    7,
                    phase="Ending",
                    min_position=0.86,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Kishotenketsu Four-Part Arc.md",
            "plot_template_kishotenketsu",
            "Kishotenketsu Four-Part Arc",
            "A four-part structure where development, contrast, and reconciliation can matter more than direct conflict.",
            slug="kishotenketsu-four-part-arc",
            family="act",
            cultural_context="Use without forcing Western antagonist escalation; the turn may be juxtaposition or recontextualization rather than combat.",
            points=[
                point(
                    "ki_introduction",
                    "Introduction",
                    "Introduces the situation, image, relationship, or premise without needing immediate conflict.",
                    1,
                    phase="Ki",
                    min_position=0,
                    max_position=0.28,
                ),
                point(
                    "sho_development",
                    "Development",
                    "Develops the initial material through variation, deepening, or accumulation.",
                    2,
                    phase="Sho",
                    min_position=0.22,
                    max_position=0.55,
                ),
                point(
                    "ten_turn",
                    "Turn",
                    "Introduces contrast, surprise, or new perspective that recontextualizes the first two parts.",
                    3,
                    phase="Ten",
                    min_position=0.5,
                    max_position=0.78,
                    failures=[
                        "The turn is treated as a mandatory battle climax instead of a contrast or reframe."
                    ],
                ),
                point(
                    "ketsu_reconciliation",
                    "Reconciliation",
                    "Combines introduction, development, and turn into a satisfying new understanding.",
                    4,
                    phase="Ketsu",
                    min_position=0.72,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Romance Relationship Arc.md",
            "plot_template_romance_relationship",
            "Romance Relationship Arc",
            "A generic relationship arc for attraction, vulnerability, rupture, repair, and emotionally satisfying closure.",
            slug="romance-relationship-arc",
            family="relationship",
            source_url="https://www.rwa.org/about-romance-fiction",
            points=[
                point(
                    "encounter",
                    "Encounter",
                    "Brings the relationship participants into meaningful contact.",
                    1,
                    phase="Opening",
                    min_position=0,
                    max_position=0.18,
                ),
                point(
                    "attraction_resistance",
                    "Attraction and resistance",
                    "Creates pull while naming why intimacy is risky or inconvenient.",
                    2,
                    phase="Opening / early middle",
                    min_position=0.12,
                    max_position=0.35,
                ),
                point(
                    "bond_deepens",
                    "Bond deepens",
                    "Shows trust, vulnerability, intimacy, or partnership becoming real.",
                    3,
                    phase="Middle",
                    min_position=0.3,
                    max_position=0.58,
                ),
                point(
                    "relationship_test",
                    "Relationship test",
                    "Forces external pressure or internal wounds against the bond.",
                    4,
                    phase="Middle",
                    min_position=0.48,
                    max_position=0.72,
                ),
                point(
                    "dark_moment",
                    "Dark moment",
                    "Makes the relationship appear genuinely impossible or too costly.",
                    5,
                    phase="Late middle",
                    min_position=0.68,
                    max_position=0.84,
                    failures=[
                        "The rupture depends only on an avoidable conversation delay with no deeper wound, value, or stake."
                    ],
                ),
                point(
                    "repair_choice",
                    "Repair choice",
                    "Requires accountability, courage, sacrifice, or changed behavior.",
                    6,
                    phase="Ending",
                    min_position=0.78,
                    max_position=0.94,
                ),
                point(
                    "satisfying_ending",
                    "Satisfying ending",
                    "Confirms an emotionally satisfying optimistic relationship state.",
                    7,
                    phase="Close",
                    min_position=0.9,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Mystery Spine.md",
            "plot_template_mystery_spine",
            "Mystery Investigation Arc",
            "A generic fair-play mystery spine. Duplicate into the book plot folder before editing.",
            slug="mystery-investigation-arc",
            family="puzzle",
            points=[
                point(
                    "crime_or_question",
                    "Crime or question",
                    "Creates the explicit puzzle the reader tracks.",
                    1,
                    phase="Opening",
                    min_position=0,
                    max_position=0.18,
                ),
                point(
                    "investigator_engages",
                    "Investigator engages",
                    "Commits a viewpoint character to seeking the truth.",
                    2,
                    phase="Opening",
                    min_position=0.08,
                    max_position=0.25,
                ),
                point(
                    "first_clue",
                    "First clue",
                    "Provides inspectable evidence, not just atmosphere.",
                    3,
                    phase="Early investigation",
                    min_position=0.12,
                    max_position=0.34,
                    failures=[
                        "The clue is only available to the detective, not the reader."
                    ],
                ),
                point(
                    "suspect_web",
                    "Suspect web",
                    "Builds plausible motives, opportunity, alibis, and competing interpretations.",
                    4,
                    phase="Investigation",
                    min_position=0.25,
                    max_position=0.62,
                ),
                point(
                    "red_herring",
                    "Red herring",
                    "Supports a plausible but wrong interpretation.",
                    5,
                    phase="Investigation",
                    min_position=0.32,
                    max_position=0.72,
                ),
                point(
                    "reveal_chain",
                    "Reveal chain",
                    "Lets the solution feel earned before confirmation.",
                    6,
                    phase="Late investigation",
                    min_position=0.58,
                    max_position=0.86,
                ),
                point(
                    "solution",
                    "Solution",
                    "Resolves the puzzle with evidence already made available.",
                    7,
                    phase="Ending",
                    min_position=0.82,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Thriller Escalation Arc.md",
            "plot_template_thriller_escalation",
            "Thriller Escalation Arc",
            "A generic thriller lens for threat, time pressure, reversal, exposure, and confrontation.",
            slug="thriller-escalation-arc",
            family="genre",
            points=[
                point(
                    "threat_declared",
                    "Threat declared",
                    "Makes the danger concrete enough to track.",
                    1,
                    phase="Opening",
                    min_position=0,
                    max_position=0.18,
                ),
                point(
                    "stakes_clock",
                    "Stakes and clock",
                    "Defines what is at risk and why delay matters.",
                    2,
                    phase="Opening",
                    min_position=0.08,
                    max_position=0.3,
                ),
                point(
                    "first_reversal",
                    "First reversal",
                    "Shows the threat adapting, expanding, or becoming personal.",
                    3,
                    phase="Early middle",
                    min_position=0.22,
                    max_position=0.42,
                ),
                point(
                    "no_safe_place",
                    "No safe place",
                    "Removes refuge, trust, or procedural protection.",
                    4,
                    phase="Middle",
                    min_position=0.38,
                    max_position=0.62,
                ),
                point(
                    "truth_exposure",
                    "Truth exposure",
                    "Reveals information that changes who or what can be trusted.",
                    5,
                    phase="Late middle",
                    min_position=0.55,
                    max_position=0.78,
                ),
                point(
                    "last_window",
                    "Last window",
                    "Narrows the problem to one dangerous, time-bound option.",
                    6,
                    phase="Final turn",
                    min_position=0.7,
                    max_position=0.9,
                ),
                point(
                    "confrontation",
                    "Confrontation",
                    "Forces direct action against the threat.",
                    7,
                    phase="Ending",
                    min_position=0.84,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Positive Character Change Arc.md",
            "plot_template_positive_character_change",
            "Positive Character Change Arc",
            "A generic arc for a character moving from a limiting belief toward a harder truth.",
            slug="positive-character-change-arc",
            family="character_arc",
            points=[
                point(
                    "want_and_lie",
                    "Want and lie",
                    "Shows what the character wants and the false belief shaping that want.",
                    1,
                    phase="Opening",
                    min_position=0,
                    max_position=0.2,
                ),
                point(
                    "need_pressure",
                    "Need pressure",
                    "Creates pressure that the old belief cannot solve.",
                    2,
                    phase="Early middle",
                    min_position=0.18,
                    max_position=0.42,
                ),
                point(
                    "truth_glimpse",
                    "Truth glimpse",
                    "Offers evidence of a better value or self-understanding.",
                    3,
                    phase="Middle",
                    min_position=0.35,
                    max_position=0.58,
                ),
                point(
                    "lie_cost",
                    "Lie cost",
                    "Makes clinging to the old belief visibly costly.",
                    4,
                    phase="Late middle",
                    min_position=0.55,
                    max_position=0.78,
                ),
                point(
                    "truth_choice",
                    "Truth choice",
                    "Requires action from the changed belief.",
                    5,
                    phase="Ending",
                    min_position=0.76,
                    max_position=0.95,
                ),
                point(
                    "changed_self",
                    "Changed self",
                    "Shows the new internal state in external behavior.",
                    6,
                    phase="Close",
                    min_position=0.9,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Negative Character Change Arc.md",
            "plot_template_negative_character_change",
            "Negative Character Change Arc",
            "A generic arc for a character rejecting truth, deepening a lie, or choosing corruption.",
            slug="negative-character-change-arc",
            family="character_arc",
            points=[
                point(
                    "want_and_wound",
                    "Want and wound",
                    "Shows the desire and pain that make the false path attractive.",
                    1,
                    phase="Opening",
                    min_position=0,
                    max_position=0.2,
                ),
                point(
                    "truth_rejected",
                    "Truth rejected",
                    "Offers a healthier alternative the character refuses or misunderstands.",
                    2,
                    phase="Early middle",
                    min_position=0.18,
                    max_position=0.42,
                ),
                point(
                    "false_gain",
                    "False gain",
                    "Rewards the destructive strategy enough to deepen commitment.",
                    3,
                    phase="Middle",
                    min_position=0.35,
                    max_position=0.58,
                ),
                point(
                    "moral_point_of_no_return",
                    "Moral point of no return",
                    "Turns the false belief into an irreversible choice.",
                    4,
                    phase="Late middle",
                    min_position=0.55,
                    max_position=0.8,
                ),
                point(
                    "collapse_or_coronation",
                    "Collapse or coronation",
                    "Shows the consequence of fully embracing the destructive path.",
                    5,
                    phase="Ending",
                    min_position=0.8,
                    max_position=1,
                ),
            ],
        ),
        template(
            "Steadfast Character Arc.md",
            "plot_template_steadfast_character",
            "Steadfast Character Arc",
            "A generic arc for a character whose stable truth changes the surrounding world.",
            slug="steadfast-character-arc",
            family="character_arc",
            points=[
                point(
                    "core_truth",
                    "Core truth",
                    "Establishes the value the character will hold under pressure.",
                    1,
                    phase="Opening",
                    min_position=0,
                    max_position=0.2,
                ),
                point(
                    "world_challenge",
                    "World challenge",
                    "Shows the world testing, dismissing, or punishing that value.",
                    2,
                    phase="Early middle",
                    min_position=0.18,
                    max_position=0.45,
                ),
                point(
                    "cost_of_steadfastness",
                    "Cost of steadfastness",
                    "Makes remaining true meaningfully expensive.",
                    3,
                    phase="Middle",
                    min_position=0.4,
                    max_position=0.7,
                ),
                point(
                    "influence_turn",
                    "Influence turn",
                    "Shows another character, institution, or system beginning to change.",
                    4,
                    phase="Late middle",
                    min_position=0.6,
                    max_position=0.85,
                ),
                point(
                    "world_changed",
                    "World changed",
                    "Pays off the steadfast value through external transformation.",
                    5,
                    phase="Ending",
                    min_position=0.82,
                    max_position=1,
                ),
            ],
        ),
    ]
