"""Remove a field from ONE entry type (#2280) — the inverse of "+ Existing field".

A type's field membership is a union twice over: across layers (every layer
that lists the field on the type adds it) and down the parent chain (a type
carries everything its parent does). Neither can subtract. So removing a field
from a type means dropping the type's OWN listing in every layer that has one,
and is refused when the field reaches the type some other way:

- `parent` — a parent type carries it; remove it there (which reaches every
  subtype) or not at all. No per-type "exclude" exists, deliberately.
- `group`  — a group application on the type generates it.
- `built_in` — the app's built-in schema lists it, which no layer can edit.

A listing in a layer above the open project is still removed — the same reach
as editing a definition at that layer — and the preview marks it `shared` so
the dialog can say so. The field definition stays, even when no type lists it
any more: it can be attached again. Values are cleared from this project's
documents of every type that loses the field (the type, and subtypes that had
it only through it).

Lives beside `schema_groups.py`'s `attach_metadata_field`; composed onto
`ProjectService` via MRO like the sibling schema mixins.
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from app.models import (
    DetachMetadataFieldRequest,
    FieldListingLayer,
    FieldRemovalPreview,
    MetadataSchema,
)
from app.services.project.errors import ProjectServiceError
from app.services.project.layers import SCHEMA_FILENAME


@dataclass
class _RemovalPlan:
    preview: FieldRemovalPreview
    before: dict[Path, dict[str, Any]]
    after: dict[Path, dict[str, Any]]


def _strip_from_type(layer_data: dict[str, Any], entry_type_id: str, key: str, field_id: str) -> bool:
    """Drop `field_id` from `entry_types.<entry_type_id>.<key>` in one layer."""
    entry_types = layer_data.get("entry_types")
    entry_type_data = entry_types.get(entry_type_id) if isinstance(entry_types, dict) else None
    listed = entry_type_data.get(key) if isinstance(entry_type_data, dict) else None
    if not isinstance(listed, list) or field_id not in listed:
        return False
    entry_type_data[key] = [candidate for candidate in listed if candidate != field_id]
    return True


class MetadataTypeMembershipMixin:
    def preview_field_removal(self, entry_type_id: str, field_id: str) -> FieldRemovalPreview:
        root = self._require_project()
        return self._plan_field_removal(root, entry_type_id.strip(), field_id.strip()).preview

    def detach_metadata_field(self, request: DetachMetadataFieldRequest) -> MetadataSchema:
        root = self._require_project()
        entry_type_id = request.entry_type_id.strip()
        field_id = request.field_id.strip()
        plan = self._plan_field_removal(root, entry_type_id, field_id)
        preview = plan.preview
        if preview.blocked_by == "parent":
            raise ProjectServiceError(
                f"{field_id} comes to {entry_type_id} from its parent type {preview.inherited_from}; "
                "remove it there, which removes it from every subtype.",
                422,
            )
        if preview.blocked_by == "built_in":
            raise ProjectServiceError(f"{field_id} is built into {entry_type_id} and can't be removed.", 422)
        if preview.blocked_by == "group":
            raise ProjectServiceError(
                f"{field_id} is generated by a group applied to {entry_type_id}; remove the group instead.",
                422,
            )

        self._validate_candidate_schema_layers(root, plan.after)
        self._write_changed_layers(plan.before, plan.after)
        self._clear_field_values_for_types(root, field_id, {entry_type_id, *preview.subtypes_losing})
        return self.read_metadata_schema()

    def _plan_field_removal(self, root: Path, entry_type_id: str, field_id: str) -> _RemovalPlan:
        schema = self.read_metadata_schema()
        entry_type = schema.entry_types.get(entry_type_id)
        if entry_type is None:
            raise ProjectServiceError(f"Unknown node type {entry_type_id}.", 404)
        if field_id not in entry_type.fields:
            raise ProjectServiceError(f"{field_id} is not a field of {entry_type_id}.", 404)

        preview = FieldRemovalPreview(
            entry_type_id=entry_type_id,
            field_id=field_id,
            other_types=sorted(
                type_id
                for type_id, definition in schema.entry_types.items()
                if type_id != entry_type_id and field_id in definition.fields
            ),
        )
        parent = schema.entry_types.get(entry_type.parent) if entry_type.parent else None
        if parent is not None and field_id in parent.fields:
            preview.blocked_by = "parent"
            preview.inherited_from = self._nearest_listing_ancestor(schema, entry_type.parent, field_id)
            return _RemovalPlan(preview, {}, {})
        if field_id not in entry_type.own_fields:
            preview.blocked_by = "group"
            return _RemovalPlan(preview, {}, {})

        layers = [layer for layer in self.collect_layers(root) if not layer.is_machine]
        before = self._chain_layers_from(root, layers[0].folder / SCHEMA_FILENAME)
        after = deepcopy(before)
        for layer in layers:
            if _strip_from_type(after[layer.folder / SCHEMA_FILENAME], entry_type_id, "fields", field_id):
                preview.listings.append(
                    FieldListingLayer(layer_id=layer.id, layer_label=layer.label, shared=not layer.is_root)
                )

        # Every type that stops carrying the field — this one and the subtypes
        # that had it only through it — drops any summary nomination of it.
        candidate = self._build_candidate_schema(root, after)
        losing = {
            type_id
            for type_id, definition in schema.entry_types.items()
            if field_id in definition.fields
            and type_id in candidate.entry_types
            and field_id not in candidate.entry_types[type_id].fields
        }
        for layer_data in after.values():
            for type_id in losing:
                _strip_from_type(layer_data, type_id, "summary_fields", field_id)
        if entry_type_id not in losing:
            # Every layer listing is gone and the type still carries the field:
            # the built-in schema lists it.
            preview.blocked_by = "built_in"
            preview.listings = []
            return _RemovalPlan(preview, {}, {})
        preview.subtypes_losing = sorted(losing - {entry_type_id})
        return _RemovalPlan(preview, before, after)

    @staticmethod
    def _nearest_listing_ancestor(schema: MetadataSchema, start: str, field_id: str) -> str:
        """The nearest type up the parent chain from `start` that lists
        `field_id` itself — where a removal would have to happen. Falls back to
        `start` when the field reaches the chain some other way (a group)."""
        seen: set[str] = set()
        type_id: str | None = start
        while type_id and type_id in schema.entry_types and type_id not in seen:
            seen.add(type_id)
            definition = schema.entry_types[type_id]
            if field_id in definition.own_fields:
                return type_id
            type_id = definition.parent
        return start

    def _clear_field_values_for_types(self, root: Path, field_id: str, entry_type_ids: set[str]) -> None:
        for path in self._entry_markdown_paths(root):
            front_matter, body = self._read_markdown_with_front_matter(path, strict=True)
            if front_matter.get("entry_type") not in entry_type_ids:
                continue
            metadata = front_matter.get("metadata")
            if not isinstance(metadata, dict) or field_id not in metadata:
                continue
            metadata.pop(field_id)
            self._write_markdown_with_front_matter(path, front_matter, body)

