/**
 * The regression surface for ADR-0044 Amendment 1 (#409, from spike #396).
 *
 * The backend's runs are rendered through the app's **real**
 * `sceneMarkdownToHtml` — which matters more than it looks, because that
 * function does not merely call `marked`: it first rewrites the `<!-- mutate: -->`,
 * `<!-- embedded-todo: -->` and `<!-- character: -->` comments into `<span data-…>`
 * atoms with regexes over the source. So a run boundary can break a **marker**,
 * not only an emphasis span.
 *
 * **Three oracles, because the obvious one is not enough.** The natural check —
 * render, strip the wrappers, compare against a plain render — passes on output
 * that is badly broken:
 *
 *     <span class="r-was"><strong>very</span> <span class="r-was">tired</strong></span>
 *
 * strips to exactly the baseline, and is also HTML no browser will build as
 * written: the parser's fixup reparents the tint, so the colour lands on the
 * wrong words — silently, in a browser, which is the one place a test is not
 * looking. So well-formedness and leak detection do the real work, and all three
 * run against all three view states, because `both` is where the runs actually
 * interleave and it has no baseline to compare against.
 *
 * The fixtures are generated by `scripts/gen_diff_fixtures.py` from the
 * production diff. Regenerate them; never edit the JSON.
 */
import { describe, expect, it } from "vitest";
import fixtures from "./diffRuns.fixtures.json";
import { renderDiffRuns } from "./diffRuns";
import { sceneMarkdownToHtml } from "./markdown";
import type { DiffRun, DiffView } from "@/lib/types";

interface Case {
  name: string;
  why: string;
  was: string;
  now: string;
  runs: DiffRun[];
}
const CASES = fixtures as unknown as Case[];
const VIEWS: DiffView[] = ["now", "was", "both"];

/**
 * Oracle 2: every tag closes inside the element that opened it. This is the
 * failure the ADR predicts and strip-and-compare cannot see.
 */
const VOID = new Set(["br", "hr", "img", "input", "meta", "link", "col", "wbr"]);
const TAG = /<!--[\s\S]*?-->|<\/?([a-zA-Z][a-zA-Z0-9-]*)\b[^>]*?(\/?)>/g;
function nestingErrors(html: string): string[] {
  const stack: string[] = [];
  const errors: string[] = [];
  for (const match of html.matchAll(TAG)) {
    if (match[0].startsWith("<!--")) continue;
    const name = match[1].toLowerCase();
    if (VOID.has(name) || match[2] === "/") continue;
    if (match[0].startsWith("</")) {
      const top = stack.pop();
      if (top !== name) errors.push(`</${name}> closes inside <${top ?? "nothing"}>`);
    } else stack.push(name);
  }
  for (const left of stack.reverse()) errors.push(`<${left}> never closed`);
  return errors;
}

/** Oracle 3: markdown syntax that reached the reader as literal text. */
function leaks(html: string): string[] {
  const text = html.replace(/<!--[\s\S]*?-->/g, "").replace(/<[^>]+>/g, "");
  return ["](", "**", "~~", "|"].filter((d) => text.includes(d)).map((d) => `literal ${d}`);
}

async function problemsFor(runs: DiffRun[], was: string, now: string): Promise<string[]> {
  const baselines: Record<string, string> = {
    now: await sceneMarkdownToHtml(now),
    was: await sceneMarkdownToHtml(was),
  };
  const baselineLeaks = new Set([...leaks(baselines.now), ...leaks(baselines.was)]);
  // Damage the DOCUMENT already carries is not damage the diff did. An author
  // can type a broken todo anchor — `<!-- /embedded-todo -->` with a word
  // inside it stops matching the marker preprocessing, so the opening span
  // never closes — and the plain render is malformed with or without a diff
  // over it. The oracle's question is whether the runs made it worse.
  const baselineNesting = new Set([...nestingErrors(baselines.now), ...nestingErrors(baselines.was)]);
  const problems: string[] = [];
  for (const view of VIEWS) {
    const html = await renderDiffRuns(runs, view);
    for (const error of nestingErrors(html)) {
      if (baselineNesting.has(error)) continue;
      problems.push(`${view}: improper nesting: ${error}\n  got: ${html.trim()}`);
    }
    for (const leak of leaks(html)) {
      if (!baselineLeaks.has(leak)) problems.push(`${view}: leaked to reader: ${leak}\n  got: ${html.trim()}`);
    }
  }
  return problems;
}

describe("diff runs render safely — the eighteen fixtures", () => {
  for (const testCase of CASES) {
    it(`${testCase.name} — ${testCase.why}`, async () => {
      // The runs must still BE the two documents, or the diff has lost words —
      // the one failure this whole feature exists to prevent.
      expect(testCase.runs.filter((r) => r.kind !== "now").map((r) => r.text).join("")).toBe(testCase.was);
      expect(testCase.runs.filter((r) => r.kind !== "was").map((r) => r.text).join("")).toBe(testCase.now);

      const problems = await problemsFor(testCase.runs, testCase.was, testCase.now);
      expect(problems.join("\n"), problems.join("\n")).toBe("");
    });
  }

  it("a single view reassembles to a plain render of that side", async () => {
    for (const testCase of CASES) {
      for (const view of ["now", "was"] as const) {
        const html = await renderDiffRuns(testCase.runs, view);
        const baseline = await sceneMarkdownToHtml(view === "now" ? testCase.now : testCase.was);
        // Stacked runs wrap rendered blocks in a container, so compare the
        // reader-visible text rather than the markup for those cases.
        const text = (value: string) => value.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
        expect(text(html), `${testCase.name}/${view}`).toBe(text(baseline));
      }
    }
  });
});

describe("Live renders unmarked", () => {
  it("no tint class appears when the runs are not used at all", async () => {
    // Live is the editable buffer, not this path — but the invariant worth
    // pinning is that a tint only ever comes from a run, so a body with no
    // runs carries no marks.
    const html = await renderDiffRuns([{ kind: "equal", text: "Plain prose, unmarked." }], "both");
    expect(html).not.toContain("r-now");
    expect(html).not.toContain("r-was");
  });
});

describe("`both` puts two copies of a marker in the DOM at once", () => {
  // Called out by the spike for slice 2 rather than left for slice 3 to
  // discover. The overlay is read-only rendered HTML that never feeds TipTap,
  // so nothing is corrupted — but anything looking a marker up by id *within
  // the overlay* would find two. Pinned so it is a known property, not a bug.
  it("is true, and is a property of the compare view rather than damage", async () => {
    const marker = (value: string) =>
      `<!-- mutate:entity=char-maren;field=mood;value=${value};id=m1 -->`;
    const runs: DiffRun[] = [
      { kind: "equal", text: "Maren did not run. " },
      { kind: "was", text: marker("stricken") },
      { kind: "now", text: marker("numb") },
      { kind: "equal", text: " She stood where she was." },
    ];
    const html = await renderDiffRuns(runs, "both");
    const ids = html.match(/data-mutation-id="m1"/g) ?? [];
    expect(ids.length).toBe(2);
    // And it is still well-formed, which is the part that would actually hurt.
    expect(nestingErrors(html)).toEqual([]);
    expect(leaks(html)).toEqual([]);
    // In a single view there is exactly one, which is what makes `both` the
    // only state with the duplicate.
    for (const view of ["now", "was"] as const) {
      const single = await renderDiffRuns(runs, view);
      expect((single.match(/data-mutation-id="m1"/g) ?? []).length).toBe(1);
    }
  });
});
