/**
 * The regression surface for ADR-0044 Amendment 1 (#409, from spike #396).
 *
 * The backend's runs are rendered through the app's **real**
 * `sceneMarkdownToHtml` — which matters more than it looks, because that
 * function does not merely call `marked`: it first rewrites the `<!-- mutate: -->`,
 * `<!-- embedded-todo: -->` and `<!-- character: -->` comments into `<span data-…>`
 * atoms with regexes over the source. So a run boundary can break a **marker**,
 * not only an emphasis span.
 *
 * **Three oracles, because the obvious one is not enough.** The natural check —
 * render, strip the wrappers, compare against a plain render — passes on output
 * that is badly broken:
 *
 *     <span class="r-was"><strong>very</span> <span class="r-was">tired</strong></span>
 *
 * strips to exactly the baseline, and is also HTML no browser will build as
 * written: the parser's fixup reparents the tint, so the colour lands on the
 * wrong words — silently, in a browser, which is the one place a test is not
 * looking. So well-formedness and leak detection do the real work, and all three
 * run against all three view states, because `both` is where the runs actually
 * interleave and it has no baseline to compare against.
 *
 * The fixtures are generated by `scripts/gen_diff_fixtures.py` from the
 * production diff. Regenerate them; never edit the JSON.
 */
import { describe, expect, it } from "vitest";
import fixtures from "./diffRuns.fixtures.json";
import { adoptRegion, groupRuns, renderDiffRuns } from "./diffRuns";
import { sceneMarkdownToHtml } from "./markdown";
import type { DiffRun, DiffView } from "@/lib/types";

interface Case {
  name: string;
  why: string;
  was: string;
  now: string;
  runs: DiffRun[];
}
const CASES = fixtures as unknown as Case[];
const VIEWS: DiffView[] = ["now", "was", "both"];

/**
 * Oracle 2: every tag closes inside the element that opened it. This is the
 * failure the ADR predicts and strip-and-compare cannot see.
 */
const VOID = new Set(["br", "hr", "img", "input", "meta", "link", "col", "wbr"]);
const TAG = /<!--[\s\S]*?-->|<\/?([a-zA-Z][a-zA-Z0-9-]*)\b[^>]*?(\/?)>/g;
function nestingErrors(html: string): string[] {
  const stack: string[] = [];
  const errors: string[] = [];
  for (const match of html.matchAll(TAG)) {
    if (match[0].startsWith("<!--")) continue;
    const name = match[1].toLowerCase();
    if (VOID.has(name) || match[2] === "/") continue;
    if (match[0].startsWith("</")) {
      const top = stack.pop();
      if (top !== name) errors.push(`</${name}> closes inside <${top ?? "nothing"}>`);
    } else stack.push(name);
  }
  for (const left of stack.reverse()) errors.push(`<${left}> never closed`);
  return errors;
}

/** Oracle 3: markdown syntax that reached the reader as literal text. */
function leaks(html: string): string[] {
  const text = html.replace(/<!--[\s\S]*?-->/g, "").replace(/<[^>]+>/g, "");
  return ["](", "**", "~~", "|"].filter((d) => text.includes(d)).map((d) => `literal ${d}`);
}


/**
 * Oracle 4: PROVENANCE. Which side is each tint claiming the text belongs to?
 *
 * The three oracles above are all provenance-blind — they count tags, strip
 * tags, or compare stripped text — so inverting every `r-now` / `r-was` class,
 * which turns every addition into a deletion and reverses the feature's central
 * claim, passed all of them. Warm means "in the scene now" and cool means "in
 * the snapshot"; a test file about that has to be able to tell them apart.
 *
 * Counting is enough and is robust: a view shows `equal` plus its own side, so
 * the marks present must be exactly the runs shown, by class and by number. A
 * swap moves them to the wrong class; a dropped wrapper changes the count.
 */
function marks(html: string): Record<string, number> {
  // The runs now carry a `data-region` and a `title` (Amendment 4), so the
  // class is no longer the whole opening tag — match up to the `>`.
  const count = (pattern: RegExp) => (html.match(pattern) ?? []).length;
  return {
    "r-now": count(/<span class="r-now"[^>]*>/g),
    "r-was": count(/<span class="r-was"[^>]*>/g),
    "blk-now": count(/<div class="blk blk-now"[^>]*>/g),
    "blk-was": count(/<div class="blk blk-was"[^>]*>/g),
  };
}

/** What `marks()` must return for these runs in this view. */
function expectedMarks(runs: DiffRun[], view: DiffView): Record<string, number> {
  const out: Record<string, number> = { "r-now": 0, "r-was": 0, "blk-now": 0, "blk-was": 0 };
  for (const run of runs) {
    if (run.kind === "equal") continue;
    if (view !== "both" && view !== run.kind) continue;
    // A stacked run carrying only a separator is dropped by the renderer.
    if (run.stacked && !run.text.trim()) continue;
    out[`${run.stacked ? "blk" : "r"}-${run.kind}`] += 1;
  }
  return out;
}

/**
 * Oracle 1, restored to structure. It had been weakened to a whitespace-collapsed
 * TEXT comparison, which cannot see a lost block boundary or a dropped `<em>`:
 * `a

b` and `a b` both reduce to "a b". Stripping the wrappers and comparing
 * the MARKUP is what the spike did and what catches those.
 *
 * Stripping has to be structural rather than a regex, because `</span>` is also
 * emitted by the marker preprocessing — so this removes each wrapper with its
 * own matching close tag, counting depth.
 */
function stripWrappers(html: string): string {
  const OPEN = /<span class="r-(?:now|was)"[^>]*>|<div class="blk blk-(?:now|was)"[^>]*>/;
  let out = html;
  for (;;) {
    const match = OPEN.exec(out);
    if (!match) return out;
    const tag = match[0].startsWith("<div") ? "div" : "span";
    const openTag = new RegExp(`<${tag}\b`, "g");
    const closeTag = new RegExp(`</${tag}>`, "g");
    let depth = 1;
    let cursor = match.index + match[0].length;
    while (depth > 0) {
      openTag.lastIndex = cursor;
      closeTag.lastIndex = cursor;
      const nextOpen = openTag.exec(out);
      const nextClose = closeTag.exec(out);
      if (!nextClose) return out; // unbalanced; oracle 2 reports it
      if (nextOpen && nextOpen.index < nextClose.index) {
        depth += 1;
        cursor = nextOpen.index + nextOpen[0].length;
      } else {
        depth -= 1;
        cursor = nextClose.index + nextClose[0].length;
        if (depth === 0) {
          out = out.slice(0, match.index) + out.slice(match.index + match[0].length, nextClose.index) + out.slice(cursor);
        }
      }
    }
  }
}

async function problemsFor(runs: DiffRun[], was: string, now: string): Promise<string[]> {
  const baselines: Record<string, string> = {
    now: await sceneMarkdownToHtml(now),
    was: await sceneMarkdownToHtml(was),
  };
  const baselineLeaks = new Set([...leaks(baselines.now), ...leaks(baselines.was)]);
  // Damage the DOCUMENT already carries is not damage the diff did. An author
  // can type a broken todo anchor — `<!-- /embedded-todo -->` with a word
  // inside it stops matching the marker preprocessing, so the opening span
  // never closes — and the plain render is malformed with or without a diff
  // over it. The oracle's question is whether the runs made it worse.
  const baselineNesting = new Set([...nestingErrors(baselines.now), ...nestingErrors(baselines.was)]);
  const problems: string[] = [];
  for (const view of VIEWS) {
    const html = await renderDiffRuns(runs, view);
    for (const error of nestingErrors(html)) {
      if (baselineNesting.has(error)) continue;
      problems.push(`${view}: improper nesting: ${error}\n  got: ${html.trim()}`);
    }
    for (const leak of leaks(html)) {
      if (!baselineLeaks.has(leak)) problems.push(`${view}: leaked to reader: ${leak}\n  got: ${html.trim()}`);
    }
  }
  return problems;
}

describe("diff runs render safely — the eighteen fixtures", () => {
  for (const testCase of CASES) {
    it(`${testCase.name} — ${testCase.why}`, async () => {
      // The runs must still BE the two documents, or the diff has lost words —
      // the one failure this whole feature exists to prevent.
      expect(testCase.runs.filter((r) => r.kind !== "now").map((r) => r.text).join("")).toBe(testCase.was);
      expect(testCase.runs.filter((r) => r.kind !== "was").map((r) => r.text).join("")).toBe(testCase.now);

      const problems = await problemsFor(testCase.runs, testCase.was, testCase.now);
      expect(problems.join("\n"), problems.join("\n")).toBe("");

      // Oracle 4: every mark on the side it belongs to, in the right number.
      for (const view of VIEWS) {
        const html = await renderDiffRuns(testCase.runs, view);
        expect(marks(html), `${testCase.name}/${view}`).toEqual(expectedMarks(testCase.runs, view));
      }
    });
  }

  it("a single view strips back to a plain render of that side, markup and all", async () => {
    for (const testCase of CASES) {
      for (const view of ["now", "was"] as const) {
        const html = await renderDiffRuns(testCase.runs, view);
        const baseline = await sceneMarkdownToHtml(view === "now" ? testCase.now : testCase.was);
        const norm = (value: string) => value.replace(/\s+/g, " ").trim();
        expect(norm(stripWrappers(html)), `${testCase.name}/${view}`).toBe(norm(baseline));
      }
    }
  });
});

describe("Live renders unmarked", () => {
  it("no tint class appears when the runs are not used at all", async () => {
    // Live is the editable buffer, not this path — but the invariant worth
    // pinning is that a tint only ever comes from a run, so a body with no
    // runs carries no marks.
    const html = await renderDiffRuns([{ kind: "equal", text: "Plain prose, unmarked." }], "both");
    expect(html).not.toContain("r-now");
    expect(html).not.toContain("r-was");
  });
});

describe("`both` puts two copies of a marker in the DOM at once", () => {
  // Called out by the spike for slice 2 rather than left for slice 3 to
  // discover. The overlay is read-only rendered HTML that never feeds TipTap,
  // so nothing is corrupted — but anything looking a marker up by id *within
  // the overlay* would find two. Pinned so it is a known property, not a bug.
  it("is true, and is a property of the compare view rather than damage", async () => {
    const marker = (value: string) =>
      `<!-- mutate:entity=char-maren;field=mood;value=${value};id=m1 -->`;
    const runs: DiffRun[] = [
      { kind: "equal", text: "Maren did not run. " },
      { kind: "was", text: marker("stricken") },
      { kind: "now", text: marker("numb") },
      { kind: "equal", text: " She stood where she was." },
    ];
    const html = await renderDiffRuns(runs, "both");
    const ids = html.match(/data-mutation-id="m1"/g) ?? [];
    expect(ids.length).toBe(2);
    // And it is still well-formed, which is the part that would actually hurt.
    expect(nestingErrors(html)).toEqual([]);
    expect(leaks(html)).toEqual([]);
    // In a single view there is exactly one, which is what makes `both` the
    // only state with the duplicate.
    for (const view of ["now", "was"] as const) {
      const single = await renderDiffRuns(runs, view);
      expect((single.match(/data-mutation-id="m1"/g) ?? []).length).toBe(1);
    }
  });
});

// A document carrying all three change shapes, and its two projections, reused
// across the adopt tests. now = everything not `was`; was = everything not `now`
// — the same reassembly the render tests pin above.
const SHAPES: DiffRun[] = [
  { kind: "equal", text: "The harbour lay " },
  { kind: "was", text: "still" }, // region 0: a modification …
  { kind: "now", text: "restless" }, // … cool + warm adjacent
  { kind: "equal", text: " under a sky. " },
  { kind: "now", text: "Nothing moved. " }, // region 1: a lone insertion
  { kind: "equal", text: "Mara counted twice" },
  { kind: "was", text: ", as taught," }, // region 2: a lone deletion
  { kind: "equal", text: "." },
];
const NOW = "The harbour lay restless under a sky. Nothing moved. Mara counted twice.";
const WAS = "The harbour lay still under a sky. Mara counted twice, as taught,.";

describe("groupRuns splits the flat runs into changed regions", () => {
  it("gives a modification both sides, and each lone change only its own", () => {
    const { regions, regionIdByRun } = groupRuns(SHAPES);
    expect(regions).toEqual([
      { id: 0, wasText: "still", nowText: "restless" },
      { id: 1, wasText: "", nowText: "Nothing moved. " },
      { id: 2, wasText: ", as taught,", nowText: "" },
    ]);
    // `equal` runs belong to no region; every changed run maps to exactly one.
    expect(regionIdByRun).toEqual([null, 0, 0, null, 1, null, 2, null]);
  });
});

describe("adoptRegion re-projects one region, and only writes when the scene changes", () => {
  it("SHAPES reassembles to its two sides — the invariant adopt rides on", () => {
    expect(SHAPES.filter((r) => r.kind !== "was").map((r) => r.text).join("")).toBe(NOW);
    expect(SHAPES.filter((r) => r.kind !== "now").map((r) => r.text).join("")).toBe(WAS);
  });

  it("restores a modification's snapshot wording (click cool)", () => {
    const { runs, body } = adoptRegion(SHAPES, 0, "was");
    expect(body).toBe("The harbour lay still under a sky. Nothing moved. Mara counted twice.");
    // The region is now plain text; the rest of the diff is untouched.
    expect(runs.filter((r) => r.kind !== "was").map((r) => r.text).join("")).toBe(body);
    expect(groupRuns(runs).regions).toHaveLength(2);
  });

  it("keeps a modification's current wording without a write (click warm)", () => {
    const { runs, body } = adoptRegion(SHAPES, 0, "now");
    expect(body).toBeNull(); // the scene already reads this way
    expect(runs.filter((r) => r.kind !== "was").map((r) => r.text).join("")).toBe(NOW);
    expect(groupRuns(runs).regions).toHaveLength(2);
  });

  it("drops a lone insertion (click warm — its only move)", () => {
    const { runs, body } = adoptRegion(SHAPES, 1, "now");
    expect(body).toBe("The harbour lay restless under a sky. Mara counted twice.");
    expect(runs.filter((r) => r.kind !== "was").map((r) => r.text).join("")).toBe(body);
  });

  it("restores a lone deletion (click cool)", () => {
    const { runs, body } = adoptRegion(SHAPES, 2, "was");
    expect(body).toBe("The harbour lay restless under a sky. Nothing moved. Mara counted twice, as taught,.");
    expect(runs.filter((r) => r.kind !== "was").map((r) => r.text).join("")).toBe(body);
  });

  it("is a no-op on an unknown region", () => {
    const { runs, body } = adoptRegion(SHAPES, 9, "was");
    expect(body).toBeNull();
    expect(runs).toBe(SHAPES);
  });
});

describe("each changed run carries the action as its title (Amendment 4)", () => {
  // The tooltip is the whole discoverability affordance — no banner, no glyph —
  // so the words are a contract, not decoration. A lone insertion says *remove*,
  // and that is what makes the one asymmetry (warm keeps, but a lone insertion
  // drops) legible at the point of the click.
  it("cool restores, warm keeps, and a lone insertion removes", async () => {
    const html = await renderDiffRuns(SHAPES, "both");
    expect(html).toContain('<span class="r-was" data-region="0" title="Restore this">still</span>');
    expect(html).toContain('<span class="r-now" data-region="0" title="Keep this">restless</span>');
    expect(html).toContain('<span class="r-now" data-region="1" title="Remove this">Nothing moved. </span>');
    expect(html).toContain('<span class="r-was" data-region="2" title="Restore this">, as taught,</span>');
  });
});
