// The Remove dialog for a type's field (#2280), as data. "Remove" takes the
// field off THIS type only; a checkbox widens it to deleting the field
// everywhere (definition + every value). When the type can't drop the field
// on its own — a parent type, a group or the built-in schema supplies it —
// the dialog offers only the delete-everywhere path and says why.
import type { FieldRemovalPreview } from "@/lib/types";

export type FieldRemovalDialog = {
  title: string;
  message: string;
  details: string[];
  confirmLabel: string;
  // Absent when the type can't drop the field alone: confirming then deletes
  // everywhere, with no choice to make.
  option?: { label: string; confirmLabel: string };
  deleteOnly: boolean;
};

const DELETE_EVERYWHERE = "Delete everywhere";

export function fieldRemovalDialog(
  preview: FieldRemovalPreview,
  fieldName: string,
  typeName: (entryTypeId: string) => string,
): FieldRemovalDialog {
  const type = typeName(preview.entry_type_id);
  const others = preview.other_types.map(typeName);

  if (preview.blocked_by) {
    const reason = {
      parent: `"${fieldName}" comes to ${type} from its parent type ${typeName(preview.inherited_from ?? "")}, so it can only be removed there.`,
      group: `"${fieldName}" is generated by a group applied to ${type}; remove the group to remove it.`,
      built_in: `"${fieldName}" is built into ${type} and can't be removed from it.`,
    }[preview.blocked_by];
    return {
      title: "Delete Field",
      message: `${reason} Delete "${fieldName}" everywhere instead? This removes the field definition and its value from every document using it.`,
      details: others.length ? [`Also used by: ${others.join(", ")}`] : [],
      confirmLabel: DELETE_EVERYWHERE,
      deleteOnly: true,
    };
  }

  const details = preview.listings
    .filter((listing) => listing.shared)
    .map(
      (listing) =>
        `Listed at ${listing.layer_label}: every project that inherits ${listing.layer_label} loses it on ${type} too.`,
    );
  if (preview.subtypes_losing.length) {
    details.push(`Also removed from ${preview.subtypes_losing.map(typeName).join(", ")}, which get it only through ${type}.`);
  }
  return {
    title: "Remove Field",
    message:
      `Remove "${fieldName}" from ${type}? Its value is cleared from ${type} documents. ` +
      `The field stays defined${others.length ? " and on its other types" : ""}.`,
    details,
    confirmLabel: "Remove from type",
    option: {
      label: others.length
        ? `Delete "${fieldName}" everywhere instead (also from ${others.join(", ")})`
        : `Delete the "${fieldName}" field definition too`,
      confirmLabel: DELETE_EVERYWHERE,
    },
    deleteOnly: false,
  };
}
